baseurl = "https://kimsdatascienceblog.netlify.com/"
languageCode = "en-US"
title = "Kimberly Staudt"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "kimberly.jpg"
  author = "Kimberly Staudt"
  description = "A Data Science Blog"

  # Custom assets can be linked with their paths relative to public/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kstaud85"
  Email         = "kstaud85@lakers.mercyhurst.edu"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

